sample:
	g++ -o sample sample.cpp -lm -framework OpenGL -framework GLUT -Wno-deprecated-declarations -Wno-c++11-compat-deprecated-writable-strings 
original:
	g++ -o original originalSample.cpp -lm -framework OpenGL -framework GLUT -Wno-deprecated-declarations -Wno-c++11-compat-deprecated-writable-strings 
clean:
	rm -f sample
	rm -f original
